# -*- coding: utf-8 -*-
"""ICT202-A2-35523915.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GHsD2PnaE-TFNhOgZJdo9puA_Eq4HxHR

#ICT202 - Assignmnet 2
Natural language processing

#1. setup and data loading

1.1 import libraries
"""

# Install the BERTopic library
!pip install bertopic
!pip install gensim

# Import necessary libraries for data manipulation and visualization
import pandas as pd
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import BERTopic for topic modeling
from bertopic import BERTopic

# Import NLTK for text preprocessing and download necessary data
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab') # Added punkt_tab download

# Imports for text preprocessing
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

"""1.2 load Raw CSV Files (10-14 June 2023)"""

# Mount Google Drive to access files stored there
from google.colab import drive
drive.mount('/content/drive')

# Import the os module for interacting with the operating system, specifically for listing directory contents
import os

# Walk through the Google Drive directory to list all subdirectories and files
# This helps in verifying file paths and locating data
for dirpath, dirnames, filenames in os.walk('/content/drive/MyDrive/'):
    print(f"Directory: {dirpath}")
    if dirnames:
        print(f"  Subdirectories: {dirnames}")
    if filenames:
        print(f"  Files: {filenames}")

# Define the path to the data directory within Google Drive
data_path = Path("/content/drive/MyDrive/Colab Notebooks/Ukraine_Twetter")

# List of CSV files to be loaded
files =  [
    "20230610_UkraineCombinedTweetsDeduped.csv",
    "20230611_UkraineCombinedTweetsDeduped.csv",
    "20230612_UkraineCombinedTweetsDeduped.csv",
    "20230613_UkraineCombinedTweetsDeduped.csv",
    "20230614_UkraineCombinedTweetsDeduped.csv"
]

""" 1.3 Initial Inspection (head, shape, columns, language counts)"""

dfs = []

for file_name in files:
    file_path = data_path / file_name
    df = pd.read_csv(file_path)
    dfs.append(df)

combined_df = pd.concat(dfs, ignore_index=True)

print("First 5 rows of combined_df:")
display(combined_df.head())

print(f"Shape of combined_df: {combined_df.shape}")

# 2. CLEAN + MAKE clean_tweets
processed_df = combined_df.copy()

if 'language' in processed_df.columns:
    processed_df = processed_df.dropna(subset=['language'])
    processed_df = processed_df[processed_df['language'].str.lower() == 'en']

processed_df = processed_df.dropna(subset=['text'])
processed_df = processed_df.drop_duplicates(subset=['text'])
processed_df = processed_df[processed_df['text'].str.len() > 20]

if len(processed_df) > 10000:
    processed_df = processed_df.sample(n=10000, random_state=42)

clean_tweets = processed_df[['text']].rename(columns={'text': 'clean_text'})
print(clean_tweets.head())

# 3. TEXT PREPROCESSING
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
import re

stop_words = set(stopwords.words('english'))
ps = PorterStemmer()

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z]', ' ', text)
    words = word_tokenize(text)
    words = [ps.stem(w) for w in words if w not in stop_words and len(w) > 1]
    return ' '.join(words)

clean_tweets['processed_text'] = clean_tweets['clean_text'].apply(preprocess_text)

# docs for BERTopic and TF-IDF
docs = clean_tweets['processed_text'].tolist()

"""#2.Exploratory Data Analysis (EDA)"""

import matplotlib.pyplot as plt
import seaborn as sns

# Get topic information from BERTopic model
topic_info_df = topic_model.get_topic_info()

# Filter out the noise topic (-1)
# The 'Count' column usually represents the number of documents in each topic
filtered_topic_counts = topic_info_df[topic_info_df.Topic != -1].sort_values(by="Count", ascending=False)

# Visualize BERTopic topic frequencies
plt.figure(figsize=(14, 8))
sns.barplot(x=filtered_topic_counts.Topic, y=filtered_topic_counts.Count, palette='viridis')
plt.xlabel('BERTopic ID')
plt.ylabel('Number of Documents')
plt.title('Distribution of Documents Across BERTopic Topics (Excluding Noise)')
plt.xticks(rotation=90)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

vprocessed_df = combined_df.copy()

# language filter
if 'language' in processed_df.columns:
    processed_df = processed_df.dropna(subset=['language'])
    processed_df = processed_df[processed_df['language'].str.lower() == 'en']
else:
    print("Warning: 'language' column not found. Skipping language filtering.")

# drop NaNs and duplicates in text
processed_df = processed_df.dropna(subset=['text'])
processed_df = processed_df.drop_duplicates(subset=['text'])

# remove short tweets
processed_df = processed_df[processed_df['text'].str.len() > 20]

# sample at most 10k
if len(processed_df) > 10000:
    processed_df = processed_df.sample(n=10000, random_state=42)

# final clean_tweets
clean_tweets = processed_df[['text']].rename(columns={'text': 'clean_text'})

print(f"Original combined_df shape: {combined_df.shape}")
print(f"Processed clean_tweets shape: {clean_tweets.shape}")
display(clean_tweets.head())

"""# 3. Data Cleaning and preprocessing

- data preprocessing:
1. fillterting English tweets
2. removing duplicates and delete short tweets
3. randomaly samppling 10,000 tweets
4. renaming 'text' to 'clean_text'
5. display the dataframe

### Text Preprocessing Steps:
1.  **Case Folding**: Convert all text to lowercase.
2.  **Remove Non-Alphabetic Characters**: Remove numbers, punctuation, and other non-alphabetic symbols.
3.  **Tokenization**: Split sentences into individual words.
4.  **Remove Stop Words**: Eliminate common words (e.g., 'the', 'is', 'a') that typically do not carry significant meaning.
5.  **Stemming**: Reduce words to their root form (e.g., 'running' -> 'run').
"""

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
import re

stop_words = set(stopwords.words('english'))
ps = PorterStemmer()

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z]', ' ', text)
    words = word_tokenize(text)
    words = [ps.stem(w) for w in words if w not in stop_words and len(w) > 1]
    return ' '.join(words)

# Apply preprocessing to create the 'processed_text' column
clean_tweets['processed_text'] = clean_tweets['clean_text'].apply(preprocess_text)

# Convert the 'processed_text' column from the preprocessed DataFrame into a list of documents
# This list will be the input for the BERTopic model
docs = clean_tweets['processed_text'].tolist()

# Initialize the BERTopic model
#   language='english': Specifies the language model to use for embeddings (Sentence-BERT).
#   calculate_probabilities=True: Enables the calculation of topic probabilities for each document.
#   verbose=True: Provides detailed output during the model's training process.
topic_model = BERTopic(language = 'english', calculate_probabilities = True, verbose = True)

# Fit the BERTopic model to the documents and transform them to get topic assignments and probabilities
#   topics: A list of topic assignments for each document (-1 typically means outlier).
#   probs: A list of probabilities for each document belonging to its assigned topic.
topics, probs = topic_model.fit_transform(docs)

# Print a header for clarity
print("Unique languages and their counts in combined_df:\n")
# Display the count of each unique language in the 'language' column of the combined_df
# This helps in understanding the distribution of languages in the dataset
print(combined_df['language'].value_counts())

print(combined_df.columns)

topic_model.get_topic_info(10)

# Get general information about the first 10 topics
# The argument '10' typically means to show information for up to topic 9 (0-indexed) or a number of topics.
# If no argument is passed, it returns info for all topics.
# Displaying head() to limit output if there are many topics.
display(topic_model.get_topic_info().head(10))

# Get the specific words and their weights for topic 0
# This provides a more detailed look at the terms that define topic 0.
print("\nWords for Topic 0:")
display(topic_model.get_topic(0))

"""#4. Feature representation TF-IDF Analysis
TF-IDF (Term Frequency-Inverse Document Frequency) is a numerical statistic that is intended to reflect how important a word is to a document in a collection or corpus.
"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TF-IDF Vectorizer
# min_df ignores terms that have a document frequency strictly lower than the given threshold
# max_df ignores terms that have a document frequency strictly higher than the given threshold
tfidf_vectorizer = TfidfVectorizer(min_df=5, max_df=0.8)

# Fit and transform the documents to get the TF-IDF matrix
tfidf_matrix = tfidf_vectorizer.fit_transform(docs)

# Get feature names (words) from the vectorizer
feature_names = tfidf_vectorizer.get_feature_names_out()

print(f"Shape of TF-IDF matrix: {tfidf_matrix.shape}")
print(f"Number of unique features (words): {len(feature_names)}")

# Display the top TF-IDF scores for a sample document (e.g., the first document)
print("\nTop TF-IDF words for the first document:")
document_index = 0
feature_index = tfidf_matrix[document_index, :].nonzero()[1]
tfidf_scores = zip(feature_index, [tfidf_matrix[document_index, x] for x in feature_index])
sorted_scores = sorted(tfidf_scores, key=lambda x: x[1], reverse=True)

for word_index, score in sorted_scores[:10]: # Display top 10 words
    print(f"  {feature_names[word_index]}: {score:.4f}")

"""#5. K-Means topic modelling

Apply the K-Means clustering algorithm to the TF-IDF matrix to group tweets into 5 clusters.

"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

# Ensure 'docs' is available. 'docs' is already defined in a previous cell as clean_tweets['processed_text'].tolist()

# 1. Re-initialize TF-IDF Vectorizer to ensure tfidf_matrix is defined
tfidf_vectorizer = TfidfVectorizer(min_df=5, max_df=0.8)

# 2. Fit and transform the documents to get the TF-IDF matrix
tfidf_matrix = tfidf_vectorizer.fit_transform(docs)

print(f"Shape of TF-IDF matrix: {tfidf_matrix.shape}")
print(f"Number of unique features (words): {len(tfidf_vectorizer.get_feature_names_out())}")

# Now, apply K-Means clustering
# 2. Instantiate a KMeans object with n_clusters=5, random_state=42, and n_init='auto'
kmeans_model = KMeans(n_clusters=5, random_state=42, n_init='auto')

# 3. Fit the K-Means model to the tfidf_matrix
kmeans_model.fit(tfidf_matrix)

# 4. Get the cluster labels for each document
cluster_labels = kmeans_model.labels_

# 5. Add these cluster labels as a new column named 'kmeans_cluster' to the clean_tweets DataFrame
clean_tweets['kmeans_cluster'] = cluster_labels

print("\nK-Means clustering applied and labels added to 'clean_tweets' DataFrame.")
display(clean_tweets.head())

"""# 5. Analyze K-Means Clusters

Analyze the centroids of the K-Means clusters to identify the most representative words for each cluster, thus defining the topics found. Display the top words for each cluster.

"""

import numpy as np

# 1. Get the cluster centroids
cluster_centroids = kmeans_model.cluster_centers_

# 2. Get the feature names (words) from the TF-IDF vectorizer
feature_names = tfidf_vectorizer.get_feature_names_out()

# Number of top words to display for each cluster
num_top_words = 10

print(f"\nTop {num_top_words} words for each of the 5 K-Means Clusters:\n")

# 3. For each cluster centroid, identify the top words
for i, centroid in enumerate(cluster_centroids):
    # Sort the feature names by their weights in the centroid in descending order
    sorted_word_indices = centroid.argsort()[::-1]

    # Get the top words and their scores
    top_words = [feature_names[idx] for idx in sorted_word_indices[:num_top_words]]
    top_scores = [centroid[idx] for idx in sorted_word_indices[:num_top_words]]

    # 4. Print these top words for each cluster
    print(f"Cluster {i}:")
    for j in range(num_top_words):
        print(f"  - {top_words[j]} (Score: {top_scores[j]:.4f})")
    print("\n")

"""#6. Visualize Cluster Sizes

Generate a bar chart to visualize the distribution of documents across the identified K-Means clusters, including a legend.

"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Calculate the count of documents in each cluster
cluster_counts = clean_tweets['kmeans_cluster'].value_counts().sort_index()

# 2. Create a bar chart to visualize these cluster counts
plt.figure(figsize=(10, 6))
sns.barplot(x=cluster_counts.index, y=cluster_counts.values, palette='viridis')

# 3. Label the x-axis as 'Cluster' and the y-axis as 'Number of Documents'
plt.xlabel('Cluster')
plt.ylabel('Number of Documents')

# 4. Add a title to the chart
plt.title('Distribution of Documents Across K-Means Clusters')

# Rotate x-axis labels for better readability if needed
plt.xticks(rotation=0)

# Add a legend (though for a single bar chart, it might be redundant, but as per instruction)
# Create a dummy legend handle as sns.barplot does not directly provide one for value_counts()
plt.legend(handles=[plt.Line2D([0], [0], color='skyblue', lw=4, label='Document Count')])

# Display the plot
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

from bertopic import BERTopic
from sklearn.cluster import KMeans, DBSCAN

# BERTopic
topic_model = BERTopic()
bertopic_labels, _ = topic_model.fit_transform(docs)

pd.Series(bertopic_labels).value_counts()

"""#topic coherence scores (c_v) for BERTopic, K-Means, and DBSCAN.

"""

!pip install gensim
!pip install bertopic

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans, DBSCAN
from gensim.models.coherencemodel import CoherenceModel
from gensim.corpora.dictionary import Dictionary


# --- Ensure clean_tweets has 'processed_text', then define docs, tfidf_matrix, feature_names ---
# Assuming `clean_tweets['clean_text']` is already available from previous steps

# If 'processed_text' is not in clean_tweets, re-create it
if 'processed_text' not in clean_tweets.columns:
    # Import NLTK components for preprocessing if needed
    from nltk.corpus import stopwords
    from nltk.stem import PorterStemmer
    from nltk.tokenize import word_tokenize
    import re

    # Ensure stop_words and ps (PorterStemmer) are defined
    stop_words = set(stopwords.words('english'))
    ps = PorterStemmer()

    def preprocess_text(text):
        text = text.lower()
        text = re.sub(r'[^a-z]', ' ', text)
        words = word_tokenize(text)
        words = [ps.stem(w) for w in words if w not in stop_words and len(w) > 1]
        return ' '.join(words)

    clean_tweets['processed_text'] = clean_tweets['clean_text'].apply(preprocess_text)

docs = clean_tweets['processed_text'].tolist()

# Re-initialize TF-IDF Vectorizer and matrix
tfidf_vectorizer = TfidfVectorizer(min_df=5, max_df=0.8)
tfidf_matrix = tfidf_vectorizer.fit_transform(docs)
feature_names = tfidf_vectorizer.get_feature_names_out()

# --- Re-apply K-Means clustering and add labels to clean_tweets ---
# The number of clusters (5) and random_state (42) were used previously in ab655d1d
kmeans_model = KMeans(n_clusters=5, random_state=42, n_init='auto')
cluster_labels_kmeans = kmeans_model.fit_predict(tfidf_matrix)
clean_tweets['kmeans_cluster'] = cluster_labels_kmeans
cluster_centroids = kmeans_model.cluster_centers_ # Required for KMeans top words

# --- Re-apply DBSCAN clustering and add labels to clean_tweets ---
# eps=0.7 and min_samples=5 were used previously in c272b4fe
dbscan_model = DBSCAN(eps=0.7, min_samples=5)
cluster_labels_dbscan = dbscan_model.fit_predict(tfidf_matrix.toarray())
clean_tweets['dbscan_cluster'] = cluster_labels_dbscan

# --- Gensim coherence setup (from ZETtzyyS8Aac) ---
texts = [doc.split() for doc in docs]
dictionary = Dictionary(texts)

def coherence(top_words):
    cm = CoherenceModel(
        topics=top_words,
        texts=texts,
        dictionary=dictionary,
        coherence='c_v'
    )
    return cm.get_coherence()

num_top_words = 10

# --- BERTopic Coherence ----
# Re-instantiate and fit BERTopic to ensure it's consistent with current `docs`
topic_model = BERTopic(language='english', calculate_probabilities=True, verbose=False)
topics, probs = topic_model.fit_transform(docs)
# Update bertopic_labels for any other uses, though not directly used in coherence calculation loop
bertopic_labels = topics

bertopic_top_words = []
for topic_id in topic_model.get_topic_info().Topic.unique():
    if topic_id != -1:
        words_with_scores = topic_model.get_topic(topic_id)
        bertopic_top_words.append([word for word, score in words_with_scores])

bertopic_top_words = [topic for topic in bertopic_top_words if topic]

if len(bertopic_top_words) > 1:
    bertopic_coherence_score = coherence(bertopic_top_words)
else:
    bertopic_coherence_score = None

# --- K-Means Coherence ---
# Re-create top_words_kmeans_dict as cluster_centroids might have changed after re-applying K-Means
top_words_kmeans_dict = {}
for i, centroid in enumerate(cluster_centroids):
    sorted_word_indices = centroid.argsort()[::-1]
    top_words_kmeans_dict[i] = [feature_names[idx] for idx in sorted_word_indices[:num_top_words]]

kmeans_top_words = list(top_words_kmeans_dict.values())

if len(kmeans_top_words) > 1:
    kmeans_coherence_score = coherence(kmeans_top_words)
else:
    kmeans_coherence_score = Non

# --- DBSCAN Coherence ---
dbscan_top_words = []
unique_dbscan_clusters = clean_tweets['dbscan_cluster'].unique()

valid_dbscan_clusters = [c_id for c_id in unique_dbscan_clusters if c_id != -1 and (clean_tweets['dbscan_cluster'] == c_id).sum() >= 5]

if len(valid_dbscan_clusters) > 0:
    for cluster_id in valid_dbscan_clusters:
        # Create a boolean mask for the current cluster
        cluster_mask = (clean_tweets['dbscan_cluster'] == cluster_id)
        # Apply the mask to tfidf_matrix to get vectors for this cluster
        cluster_tfidf_vectors = tfidf_matrix[cluster_mask.values]
        if cluster_tfidf_vectors.shape[0] > 0:
            cluster_centroid_dbscan = cluster_tfidf_vectors.mean(axis=0).A1
            sorted_word_indices = cluster_centroid_dbscan.argsort()[::-1]
            top_words_for_cluster = [feature_names[idx] for idx in sorted_word_indices if cluster_centroid_dbscan[idx] > 0][:num_top_words]
            if top_words_for_cluster:
                dbscan_top_words.append(top_words_for_cluster)

if len(dbscan_top_words) > 1:
    dbscan_coherence_score = coherence(dbscan_top_words)
else:
    dbscan_coherence_score = None

# --- Display Results ---
coherence_results = pd.DataFrame({
    "Model": ["BERTopic", "KMeans", "DBSCAN"],
    "Coherence (c_v) Score": [bertopic_coherence_score, kmeans_coherence_score, dbscan_coherence_score]
})

display(coherence_results)

"""#9. Extract Example Tweets for K-Means Clusters

### Subtask:
For each of the K-Means clusters, retrieve and display a few representative original tweets to provide a qualitative understanding of the cluster content.

**Reasoning**:
To extract representative tweets for each K-Means cluster, I will create a new DataFrame, identify unique clusters, and then iterate through each cluster to retrieve its top words and sample original tweets for display.
"""

import pandas as pd
import numpy as np

# 1. Create a new DataFrame, kmeans_df, by copying clean_tweets
kmeans_df = clean_tweets.copy()

# 2. Ensure the kmeans_cluster column is present in kmeans_df (it was added in a previous step)
# If it wasn't, an error would occur, but based on notebook state, it exists.

# 3. Get the list of unique K-Means cluster IDs
unique_kmeans_clusters = kmeans_df['kmeans_cluster'].unique()
unique_kmeans_clusters.sort()

print("\nRepresentative Tweets for K-Means Clusters:\n")

# Ensure cluster_centroids and feature_names are accessible from previous steps
# (These were generated in cell 38eabbd2)
# If not, they would need to be re-run or passed as arguments.

# 4. For each unique K-Means cluster ID:
for cluster_id in unique_kmeans_clusters:
    print(f"--- K-Means Cluster {cluster_id} ---")

    # b. Retrieve and print the top 10 representative words for the current cluster.
    # This uses the cluster_centroids and feature_names from the 'Analyze K-Means Clusters' step.
    num_top_words = 10 # Defined in previous analysis step
    centroid = cluster_centroids[cluster_id]
    sorted_word_indices = centroid.argsort()[::-1]
    top_words = [feature_names[idx] for idx in sorted_word_indices[:num_top_words]]
    top_scores = [centroid[idx] for idx in sorted_word_indices[:num_top_words]]

    print("Top words:")
    for j in range(num_top_words):
        print(f"  - {top_words[j]} (Score: {top_scores[j]:.4f})")

    # c. Filter kmeans_df to select tweets belonging to the current cluster.
    cluster_tweets_df = kmeans_df[kmeans_df['kmeans_cluster'] == cluster_id]

    # d. Randomly sample 3 to 5 original tweets (clean_text column).
    num_samples = min(len(cluster_tweets_df), 5) # Sample up to 5, or all if less than 5
    if num_samples > 0:
        sampled_tweets = cluster_tweets_df['clean_text'].sample(n=num_samples, random_state=42).tolist()
    else:
        sampled_tweets = []

    # e. Print each of the sampled tweets.
    print("Sample Tweets:")
    if sampled_tweets:
        for i, tweet in enumerate(sampled_tweets):
            print(f"  Sample {i+1}: {tweet}")
    else:
        print("  No tweets found for this cluster.")
    print("\n")

# import numpy as np

# # 1. Calculate the coherence score for the BERTopic model
# # The 'docs' variable contains the preprocessed text documents.
# coherence_score = topic_model.get_topic_coherence(docs)

# # 2. Print the calculated coherence score
print(f"BERTopic Topic Coherence Score: {bertopic_coherence_score:.4f}")

# Note: The 'get_topic_coherence' method is not directly available in this BERTopic version.
# Please refer to cell fc0cdf36 for the correct coherence calculation using Gensim.

"""### New Function Placeholder

This is where you can add your new function definitions. Placing them after existing utility functions like `preprocess_text` ensures they are defined in a logical and accessible part of the notebook before being called by other operations.
"""

def my_new_function(data):
    """This is a placeholder for your new function."""
    print("New function called with data:", data)
    return data

import matplotlib.pyplot as plt

# 1. Calculate the count of documents in each cluster
cluster_counts = clean_tweets['kmeans_cluster'].value_counts().sort_index()

# 2. Create a bar chart to visualize these cluster counts
plt.figure(figsize=(10, 6))
cluster_counts.plot(kind='bar', color='skyblue')

# 3. Label the x-axis as 'Cluster' and the y-axis as 'Number of Documents'
plt.xlabel('Cluster')
plt.ylabel('Number of Documents')

# 4. Add a title to the chart
plt.title('Distribution of Documents Across K-Means Clusters')

# Rotate x-axis labels for better readability if needed
plt.xticks(rotation=0)

# Add a legend (though for a single bar chart, it might be redundant, but as per instruction)
plt.legend(['Document Count'])

# Display the plot
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

from sklearn.decomposition import PCA

# Reduce the dimensionality of the TF-IDF matrix for visualization
# PCA is chosen for its simplicity and interpretability in showing variance.
pca = PCA(n_components=2, random_state=42)
tfidf_2d = pca.fit_transform(tfidf_matrix.toarray()) # Convert sparse matrix to dense array

# Add the 2D PCA components to the clean_tweets DataFrame for easy plotting
clean_tweets['pca_one'] = tfidf_2d[:, 0]
clean_tweets['pca_two'] = tfidf_2d[:, 1]

# Create the scatter plot
plt.figure(figsize=(12, 8))
sns.scatterplot(
    x='pca_one',
    y='pca_two',
    hue='kmeans_cluster',
    palette='viridis',
    data=clean_tweets,
    legend='full',
    alpha=0.6
)

plt.title('K-Means Clusters Visualization (PCA Reduced)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""# 7. Calculate BERTopic Coherence

Calculate and display topic coherence scores for the topics identified by BERTopic. This provides a quantitative measure of topic quality.

"""

from sklearn.cluster import DBSCAN

# 1. Instantiate a DBSCAN object with eps=0.7 and min_samples=5
dbscan_model = DBSCAN(eps=0.7, min_samples=5)

# 2. Fit the DBSCAN model to the tfidf_matrix
# DBSCAN expects a dense matrix if not explicitly handling sparse matrices, so converting is safer
dbscan_model.fit(tfidf_matrix.toarray())

# 3. Get the cluster labels for each document
cluster_labels_dbscan = dbscan_model.labels_

# 4. Add these cluster labels as a new column named 'dbscan_cluster' to the clean_tweets DataFrame
clean_tweets['dbscan_cluster'] = cluster_labels_dbscan

print("DBSCAN clustering applied and labels added to 'clean_tweets' DataFrame.")
display(clean_tweets.head())

import numpy as np

# 1. Get the unique cluster labels from the 'dbscan_cluster' column
unique_labels = np.unique(clean_tweets['dbscan_cluster'])

# 2. Calculate the number of clusters, excluding the noise points (labeled as -1)
num_clusters = len(unique_labels) - (1 if -1 in unique_labels else 0)

# 3. Calculate the number of noise points
noise_points = np.sum(clean_tweets['dbscan_cluster'] == -1)

# 4. Calculate the number of documents assigned to each cluster, excluding noise points
cluster_counts_dbscan = clean_tweets['dbscan_cluster'].value_counts().sort_index()

print(f"\nDBSCAN Clustering Analysis:")
print(f"Total number of identified clusters (excluding noise): {num_clusters}")
print(f"Number of noise points: {noise_points}")
print("\nDocument counts per cluster (excluding noise points):")

# Print counts for actual clusters
for cluster_label, count in cluster_counts_dbscan.items():
    if cluster_label != -1:
        print(f"  Cluster {cluster_label}: {count} documents")

"""# 8. Visualize BERTopic Top Word Distributions

### Subtask:
For each of the main BERTopic topics, visualize the distribution of its top representative words and their scores.
"""

# Make a copy of the combined_df to avoid modifying the original data
processed_df = combined_df.copy()

# 1. Filter to English tweets (assuming 'language' column exists and 'en' is the value)
# Check if the 'language' column exists in the DataFrame
if 'language' in processed_df.columns:
    # Drop rows where 'language' is NaN to ensure accurate filtering
    processed_df = processed_df.dropna(subset=['language'])
    # Filter the DataFrame to keep only English tweets ('en')
    processed_df = processed_df[processed_df['language'].str.lower() == 'en']
else:
    print("Warning: 'language' column not found. Skipping language filtering.")

# 2. Remove duplicates based on the 'text' column
# Drop rows where 'text' is NaN before checking for duplicates
processed_df = processed_df.dropna(subset=['text'])
# Remove duplicate tweets based on their 'text' content
processed_df = processed_df.drop_duplicates(subset=['text'])

# 3. Remove very short tweets (e.g., less than 20 characters)
# Filter out tweets shorter than 20 characters, as they might not provide meaningful topics
processed_df = processed_df[processed_df['text'].str.len() > 20]

# 4. Immediately randomly sample to at most 10,000 tweets
# If the number of processed tweets exceeds 10,000, randomly sample 10,000 for efficiency
if len(processed_df) > 10000:
    processed_df = processed_df.sample(n=10000, random_state=42)

# 5. Keep only clean_text (renaming 'text' column to 'clean_text' and selecting only it)
# Select the 'text' column and rename it to 'clean_text' for clarity
clean_tweets = processed_df[['text']].rename(columns={'text': 'clean_text'})

# Print the shapes of the original and processed DataFrames to show the impact of preprocessing
print(f"Original combined_df shape: {combined_df.shape}")
print(f"Processed clean_tweets shape: {clean_tweets.shape}")
# Display the first few rows of the cleaned tweets
display(clean_tweets.head())

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Get top N topics to visualize their word distributions
# Using the filtered_topic_counts from the previous cell
num_topics_to_visualize = 10  # Visualize top 10 topics
top_topics_info = filtered_topic_counts.head(num_topics_to_visualize)

print(f"\nVisualizing top words for the top {num_topics_to_visualize} BERTopic topics:\n")

for index, row in top_topics_info.iterrows():
    topic_id = row['Topic']
    topic_name = row['Name']

    # Get the words and their scores for the current topic
    # BERTopic's get_topic returns a list of (word, score) tuples
    topic_words = topic_model.get_topic(topic_id)

    if topic_words:
        words = [word[0] for word in topic_words]
        scores = [word[1] for word in topic_words]

        # Create a DataFrame for easy plotting
        df_topic_words = pd.DataFrame({'Word': words, 'Score': scores})

        plt.figure(figsize=(10, 6))
        sns.barplot(x='Score', y='Word', data=df_topic_words.head(10), palette='magma') # Display top 10 words for each topic
        plt.title(f'BERTopic Topic {topic_id}: {topic_name}\nTop 10 Words and Scores')
        plt.xlabel('Word Score (c-TF-IDF)')
        plt.ylabel('Word')
        plt.grid(axis='x', linestyle='--', alpha=0.7)
        plt.tight_layout()
        plt.show()
    else:
        print(f"No words found for BERTopic Topic {topic_id}.\n")

"""#10. Apply DBSCAN Clustering

Apply the DBSCAN clustering algorithm to the `tfidf_matrix` with `eps=0.7` and `min_samples=5`, and then add the resulting cluster labels to the `clean_tweets` DataFrame.

"""

from sklearn.cluster import DBSCAN

# 1. Instantiate a DBSCAN object with eps=0.7 and min_samples=5
dbscan_model = DBSCAN(eps=0.7, min_samples=7)

# 2. Fit the DBSCAN model to the tfidf_matrix
# DBSCAN expects a dense matrix if not explicitly handling sparse matrices, so converting is safer
dbscan_model.fit(tfidf_matrix.toarray())

# 3. Get the cluster labels for each document
cluster_labels_dbscan = dbscan_model.labels_

# 4. Add these cluster labels as a new column named 'dbscan_cluster' to the clean_tweets DataFrame
clean_tweets['dbscan_cluster'] = cluster_labels_dbscan

print("DBSCAN clustering applied and labels added to 'clean_tweets' DataFrame.")
display(clean_tweets.head())

"""#11. Analyze DBSCAN Clusters

Analyze the results of DBSCAN, including the number of clusters identified (excluding noise points) and the number of noise points.

"""

import numpy as np

# 1. Get the unique cluster labels from the 'dbscan_cluster' column
unique_labels = np.unique(clean_tweets['dbscan_cluster'])

# 2. Calculate the number of clusters, excluding the noise points (labeled as -1)
num_clusters = len(unique_labels) - (1 if -1 in unique_labels else 0)

# 3. Calculate the number of noise points
noise_points = np.sum(clean_tweets['dbscan_cluster'] == -1)

# 4. Calculate the number of documents assigned to each cluster, excluding noise points
cluster_counts_dbscan = clean_tweets['dbscan_cluster'].value_counts().sort_index()

print(f"\nDBSCAN Clustering Analysis:")
print(f"Total number of identified clusters (excluding noise): {num_clusters}")
print(f"Number of noise points: {noise_points}")
print("\nDocument counts per cluster (excluding noise points):")

# Print counts for actual clusters
for cluster_label, count in cluster_counts_dbscan.items():
    if cluster_label != -1:
        print(f"  Cluster {cluster_label}: {count} documents")

"""#12. Visualize DBSCAN Clusters

Reduce the dimensionality of the TF-IDF matrix using PCA (Principal Component Analysis) to 2 components. Then, create a scatter plot to visualize the DBSCAN clusters, using different colors for each cluster and marking noise points distinctly. Include appropriate labels and a legend.

"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA

# Ensure tfidf_matrix is available (it is from previous cells)
# Reduce the dimensionality of the TF-IDF matrix for visualization
# PCA is chosen for its simplicity and interpretability in showing variance.
pca = PCA(n_components=2, random_state=42)
tfidf_2d = pca.fit_transform(tfidf_matrix.toarray()) # Convert sparse matrix to dense array

# Add the 2D PCA components to the clean_tweets DataFrame for easy plotting
clean_tweets['pca_one'] = tfidf_2d[:, 0]
clean_tweets['pca_two'] = tfidf_2d[:, 1]

# 1) Work with existing labels
labels = clean_tweets['dbscan_cluster'].values

# Identify noise and non-noise
noise_mask = labels == -1
cluster_mask = ~noise_mask

# 2) Find the largest non-noise clusters
cluster_labels, counts = np.unique(labels[cluster_mask], return_counts=True)
# Sort by size descending
sorted_idx = np.argsort(-counts)
cluster_labels = cluster_labels[sorted_idx]
counts = counts[sorted_idx]

top_k = 10   # show top 10 clusters clearly (increased from 5)
top_clusters = set(cluster_labels[:top_k])

# 3) Build a helper column for plotting
def map_label(l):
    if l == -1:
        return 'Noise'
    elif l in top_clusters:
        return f'Cluster {l}'
    else:
        return 'Other'

clean_tweets['dbscan_plot_label'] = [map_label(l) for l in labels]

plt.figure(figsize=(12, 9)) # Slightly increased figure size

# Plot noise and "other" first (faint and distinct colors)
sns.scatterplot(
    x='pca_one',
    y='pca_two',
    data=clean_tweets[clean_tweets['dbscan_plot_label'].isin(['Noise', 'Other'])],
    hue='dbscan_plot_label',
    palette={'Noise': 'darkgray', 'Other': 'lightsteelblue'}, # Changed palette for better distinction
    legend='brief',
    s=15, # Slightly larger for better visibility
    alpha=0.3 # Keep them subtle
)

# Plot top clusters with strong colours
sns.scatterplot(
    x='pca_one',
    y='pca_two',
    data=clean_tweets[clean_tweets['dbscan_plot_label'].str.startswith('Cluster')],
    hue='dbscan_plot_label',
    palette='tab10', # 'tab10' has 10 distinct colors, suitable for top_k=10
    s=60, # Emphasize top clusters with larger size
    alpha=0.9 # Make top clusters more opaque
)

plt.title('DBSCAN Clusters (PCA-reduced, top clusters highlighted)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

"""#13. Apply DBSCAN on TF-IDF

**Reasoning**:
Now that the markdown header has been created, I will move the existing DBSCAN application code cell (`8cf54cd9`) to be directly underneath this new header as per the instructions.
"""

from sklearn.cluster import DBSCAN
from sklearn.feature_extraction.text import TfidfVectorizer

# Ensure 'docs' is available (it's already set from clean_tweets['processed_text'].tolist() in previous steps)

# Re-initialize TF-IDF Vectorizer to ensure tfidf_matrix is defined
tfidf_vectorizer = TfidfVectorizer(min_df=5, max_df=0.8)

# Fit and transform the documents to get the TF-IDF matrix
tfidf_matrix = tfidf_vectorizer.fit_transform(docs)

# 1. Instantiate a DBSCAN object with eps=0.7 and min_samples=5
dbscan_model = DBSCAN(eps=0.7, min_samples=5)

# 2. Fit the DBSCAN model to the tfidf_matrix
# DBSCAN expects a dense matrix if not explicitly handling sparse matrices, so converting is safer
dbscan_model.fit(tfidf_matrix.toarray())

# 3. Get the cluster labels for each document
cluster_labels_dbscan = dbscan_model.labels_

# 4. Add these cluster labels as a new column named 'dbscan_cluster' to the clean_tweets DataFrame
clean_tweets['dbscan_cluster'] = cluster_labels_dbscan

print("DBSCAN clustering applied and labels added to 'clean_tweets' DataFrame.")
display(clean_tweets.head())

"""# Comparative analysis: BERTopic vs K-Means vs DBSCAN"""

!pip install bertopic sentence-transformers

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = model.encode(docs, show_progress_bar=True)

from bertopic import BERTopic
from sklearn.cluster import KMeans, DBSCAN

# BERTopic
topic_model = BERTopic()
bertopic_labels, _ = topic_model.fit_transform(docs)

# K-Means
kmeans = KMeans(n_clusters=10, random_state=42)
kmeans_labels = kmeans.fit_predict(embeddings)

# DBSCAN
dbscan = DBSCAN(eps=0.5, min_samples=5)
dbscan_labels = dbscan.fit_predict(embeddings)

from sklearn.metrics import silhouette_score, davies_bouldin_score

def compute_metrics(X, labels):
    # DBSCAN may produce all -1 (noise)
    if len(set(labels)) <= 1:
        return None, None
    return (
        silhouette_score(X, labels),
        davies_bouldin_score(X, labels)
    )

ber_sil, ber_db = compute_metrics(embeddings, bertopic_labels)
km_sil, km_db = compute_metrics(embeddings, kmeans_labels)
db_sil, db_db = compute_metrics(embeddings, dbscan_labels)

import pandas as pd

results = pd.DataFrame({
    "Model": ["BERTopic", "KMeans", "DBSCAN"],
    "Silhouette Score": [ber_sil, km_sil, db_sil],
    "Davies-Bouldin Index": [ber_db, km_db, db_db]
})

results

"""# UMAP visualizations"""

import umap.umap_ as umap
import matplotlib.pyplot as plt

reducer = umap.UMAP(random_state=42)
umap_embeddings = reducer.fit_transform(embeddings)

def plot_clusters(umap_data, labels, title):
    plt.figure(figsize=(8,6))
    plt.scatter(umap_data[:,0], umap_data[:,1], c=labels, cmap='Spectral', s=5)
    plt.title(title)
    plt.show()

plot_clusters(umap_embeddings, bertopic_labels, "BERTopic Clusters")
plot_clusters(umap_embeddings, kmeans_labels, "KMeans Clusters")
plot_clusters(umap_embeddings, dbscan_labels, "DBSCAN Clusters")

from sklearn.metrics import calinski_harabasz_score

def extra_metrics(X, labels):
    if len(set(labels)) <= 1:
        return None, None, None
    sil = silhouette_score(X, labels)
    db = davies_bouldin_score(X, labels)
    ch = calinski_harabasz_score(X, labels)
    return sil, db, ch

ber_sil, ber_db, ber_ch = extra_metrics(embeddings, bertopic_labels)
km_sil, km_db, km_ch = extra_metrics(embeddings, kmeans_labels)
db_sil, db_db, db_ch = extra_metrics(embeddings, dbscan_labels)

pd.DataFrame({
    "Model": ["BERTopic", "KMeans", "DBSCAN"],
    "Silhouette": [ber_sil, km_sil, db_sil],
    "Davies-Bouldin": [ber_db, km_db, db_db],
    "Calinski-Harabasz": [ber_ch, km_ch, db_ch]
})

"""#topic coherence for BERTopic vs K-Means vs DBSCAN"""

# Install the gensim library if not already installed
!pip install gensim

from gensim.models.coherencemodel import CoherenceModel
from gensim.corpora.dictionary import Dictionary

# Assuming 'docs' is the list of preprocessed text documents (from a previous cell)
# Each document in 'docs' is a string of space-separated words. We need to split them into lists of words.
texts = [doc.split() for doc in docs]  # Use 'docs' as defined earlier
dictionary = Dictionary(texts)

def compute_coherence_for_topics(topic_words):
    cm = CoherenceModel(
        topics=topic_words,
        texts=texts,
        dictionary=dictionary,
        coherence='c_v'
    )
    return cm.get_coherence()

qual_rows = []

# Re-extract top words for K-Means clusters
# This assumes `cluster_centroids` and `feature_names` are still available from cell 38eabbd2
num_top_words = 10
top_words_kmeans_dict = {}
for i, centroid in enumerate(cluster_centroids):
    sorted_word_indices = centroid.argsort()[::-1]
    top_words_kmeans_dict[i] = [feature_names[idx] for idx in sorted_word_indices[:num_top_words]]

for cluster_id in [0, 1, 2]:  # example, you can adjust the cluster_ids
    # Use clean_tweets (or kmeans_df if it's preferred) instead of combined_df
    # and 'clean_text' column for the original tweets
    sample_docs = clean_tweets[clean_tweets["kmeans_cluster"] == cluster_id]["clean_text"].head(3).tolist()
    qual_rows.append({
        "Model": "KMeans",
        "Cluster": cluster_id,
        "Top Words": ", ".join(top_words_kmeans_dict[cluster_id]),
        "Example Tweets": sample_docs
    })

pd.DataFrame(qual_rows)

from gensim.models.coherencemodel import CoherenceModel
from gensim.corpora.dictionary import Dictionary

texts = [doc.split() for doc in docs]
dictionary = Dictionary(texts)

def coherence(top_words):
    cm = CoherenceModel(
        topics=top_words,
        texts=texts,
        dictionary=dictionary,
        coherence='c_v'
    )
    return cm.get_coherence()

    noise_ratio = list(dbscan_labels).count(-1) / len(dbscan_labels)


pd.Series(kmeans_labels).value_counts()
pd.Series(bertopic_labels).value_counts()
pd.Series(dbscan_labels).value_counts()

